create or replace view public.v_broadcast_players_public as  WITH base AS (
         SELECT p.sports_gamer_league_id,
            p.sports_gamer_team_id,
            p.team_name_in_league,
            p.sports_gamer_player_id,
            p.display_gamertag,
            p.player_number,
            p.player_country,
            p.player_image,
            p.roster_preferred_position_abbreviation,
            p.regular_skater_position_abbreviation,
            p.playoff_skater_position_abbreviation,
            p.regular_skater_games,
            p.regular_goals,
            p.regular_assists,
            p.regular_points,
            p.playoff_skater_games,
            p.playoff_goals,
            p.playoff_assists,
            p.playoff_points,
            p.regular_goalie_games,
            p.regular_goalie_goals_against_average,
            p.regular_goalie_shutouts,
            p.playoff_goalie_games,
            p.playoff_goalie_goals_against_average,
            p.playoff_goalie_shutouts,
            p.sports_gamer_player_url,
            p.regular_faceoff_wins,
            p.regular_faceoff_losses,
            p.playoff_faceoff_wins,
            p.playoff_faceoff_losses,
            COALESCE(p.regular_goalie_save_percentage,
                CASE
                    WHEN (COALESCE(p.regular_goalie_saves, 0::bigint) + COALESCE(p.regular_goalie_goals_allowed, 0::bigint)) > 0 THEN p.regular_goalie_saves::numeric / (p.regular_goalie_saves + p.regular_goalie_goals_allowed)::numeric
                    ELSE NULL::numeric
                END)::numeric(12,4) AS regular_goalie_save_percentage,
            COALESCE(p.playoff_goalie_save_percentage,
                CASE
                    WHEN (COALESCE(p.playoff_goalie_saves, 0::bigint) + COALESCE(p.playoff_goalie_goals_allowed, 0::bigint)) > 0 THEN p.playoff_goalie_saves::numeric / (p.playoff_goalie_saves + p.playoff_goalie_goals_allowed)::numeric
                    ELSE NULL::numeric
                END)::numeric(12,4) AS playoff_goalie_save_percentage,
            p.regular_penalty_minutes,
            p.playoff_penalty_minutes,
            p.regular_takeaways,
            p.regular_interceptions,
            p.regular_blocked_shots,
            p.playoff_takeaways,
            p.playoff_interceptions,
            p.playoff_blocked_shots,
            p.regular_hits,
            p.playoff_hits
           FROM sportsgamer_team_player_stats p
          WHERE p.sports_gamer_league_id = ANY (ARRAY[520::bigint, 523::bigint, 524::bigint, 525::bigint, 526::bigint, 527::bigint, 529::bigint, 532::bigint])
        UNION ALL
         SELECT r.sports_gamer_league_id,
            r.sports_gamer_team_id,
            COALESCE(t.team_name, 'TEAM '::text || r.sports_gamer_team_id::text) AS team_name_in_league,
            r.sports_gamer_player_id,
            r.display_gamertag,
            r.player_number::bigint AS player_number,
            r.player_country,
            r.player_image,
            r.preferred_position AS roster_preferred_position_abbreviation,
            NULL::text AS regular_skater_position_abbreviation,
            NULL::text AS playoff_skater_position_abbreviation,
            NULL::bigint AS regular_skater_games,
            NULL::bigint AS regular_goals,
            NULL::bigint AS regular_assists,
            NULL::bigint AS regular_points,
            NULL::bigint AS playoff_skater_games,
            NULL::bigint AS playoff_goals,
            NULL::bigint AS playoff_assists,
            NULL::bigint AS playoff_points,
            NULL::bigint AS regular_goalie_games,
            NULL::numeric AS regular_goalie_goals_against_average,
            NULL::bigint AS regular_goalie_shutouts,
            NULL::bigint AS playoff_goalie_games,
            NULL::numeric AS playoff_goalie_goals_against_average,
            NULL::bigint AS playoff_goalie_shutouts,
            NULL::text AS sports_gamer_player_url,
            NULL::bigint AS regular_faceoff_wins,
            NULL::bigint AS regular_faceoff_losses,
            NULL::bigint AS playoff_faceoff_wins,
            NULL::bigint AS playoff_faceoff_losses,
            NULL::numeric(12,4) AS regular_goalie_save_percentage,
            NULL::numeric(12,4) AS playoff_goalie_save_percentage,
            NULL::bigint AS regular_penalty_minutes,
            NULL::bigint AS playoff_penalty_minutes,
            NULL::bigint AS regular_takeaways,
            NULL::bigint AS regular_interceptions,
            NULL::bigint AS regular_blocked_shots,
            NULL::bigint AS playoff_takeaways,
            NULL::bigint AS playoff_interceptions,
            NULL::bigint AS playoff_blocked_shots,
            NULL::bigint AS regular_hits,
            NULL::bigint AS playoff_hits
           FROM sportsgamer_league_roster_current r
             LEFT JOIN sportsgamer_league_teams_current t ON t.sports_gamer_league_id = r.sports_gamer_league_id AND t.sports_gamer_team_id = r.sports_gamer_team_id
          WHERE (r.sports_gamer_league_id = ANY (ARRAY[520::bigint, 523::bigint, 524::bigint, 525::bigint, 526::bigint, 527::bigint, 529::bigint, 532::bigint])) AND COALESCE(r.is_available, true) AND NOT (EXISTS ( SELECT 1
                   FROM sportsgamer_team_player_stats p
                  WHERE p.sports_gamer_league_id = r.sports_gamer_league_id AND p.sports_gamer_team_id = r.sports_gamer_team_id AND p.sports_gamer_player_id = r.sports_gamer_player_id))
        )
 SELECT b.sports_gamer_league_id,
    b.sports_gamer_team_id,
    b.team_name_in_league,
    b.sports_gamer_player_id,
    b.display_gamertag,
    b.player_number,
    b.player_country,
    COALESCE(profile.image_url, b.player_image) AS player_image,
    b.roster_preferred_position_abbreviation,
    b.regular_skater_position_abbreviation,
    b.playoff_skater_position_abbreviation,
    b.regular_skater_games,
    b.regular_goals,
    b.regular_assists,
    b.regular_points,
    b.playoff_skater_games,
    b.playoff_goals,
    b.playoff_assists,
    b.playoff_points,
    b.regular_goalie_games,
    b.regular_goalie_goals_against_average,
    b.regular_goalie_shutouts,
    b.playoff_goalie_games,
    b.playoff_goalie_goals_against_average,
    b.playoff_goalie_shutouts,
    b.sports_gamer_player_url,
    b.regular_faceoff_wins,
    b.regular_faceoff_losses,
    b.playoff_faceoff_wins,
    b.playoff_faceoff_losses,
    b.regular_goalie_save_percentage,
    b.playoff_goalie_save_percentage,
    b.regular_penalty_minutes,
    b.playoff_penalty_minutes,
    b.regular_takeaways,
    b.regular_interceptions,
    b.regular_blocked_shots,
    b.playoff_takeaways,
    b.playoff_interceptions,
    b.playoff_blocked_shots,
    b.regular_hits,
    b.playoff_hits,
    exists (select 1 from public.sportsgamer_league_roster_current current_roster
      where current_roster.sports_gamer_league_id=b.sports_gamer_league_id
        and current_roster.sports_gamer_team_id=b.sports_gamer_team_id
        and current_roster.sports_gamer_player_id=b.sports_gamer_player_id
        and coalesce(current_roster.is_available,true)) as is_current_roster
   FROM base b
     LEFT JOIN LATERAL ( SELECT p.image_url
           FROM v_ehockey_player_self_profiles_public p
          WHERE p.sports_gamer_player_id = b.sports_gamer_player_id::text AND NULLIF(btrim(p.image_url), ''::text) IS NOT NULL
          ORDER BY p.approved_at DESC NULLS LAST, p.updated_at DESC NULLS LAST
         LIMIT 1) profile ON true;
