(()=>{'use strict';const $=id=>document.getElementById(id),cfg=window.EHOCKEY_CONFIG,endpoint=cfg.supabaseUrl+'/functions/v1/swn-image-upload',token=location.hash.slice(1);let info,previewUrl,timer,searchSequence=0;
async function api(action,data={}){const multipart=data instanceof FormData;if(multipart){data.set('action',action);data.set('token',token);}const response=await fetch(endpoint,{method:'POST',headers:multipart?{apikey:cfg.supabasePublishableKey}:{apikey:cfg.supabasePublishableKey,'Content-Type':'application/json'},body:multipart?data:JSON.stringify({action,token,...data})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Det gick inte att skicka. Försök igen.');return result;}
function error(e){$('uploadStatus').textContent=e.message;}
async function init(){try{info=await api('info');$('linkName').textContent=info.name;$('linkState').textContent=info.remaining+' uppladdningar återstår på den här länken.';$('consentText').textContent=info.consentText;$('uploadForm').hidden=info.remaining<1;if(info.remaining<1)$('linkState').textContent='Alla tillåtna uppladdningar är använda. Kontakta SWNWORKS om du behöver skicka fler.';const presets=info.presets||[];$('presetField').hidden=!presets.length;$('presetGT').replaceChildren();for(const [value,label] of [['','Välj ditt GT'],...presets.map(x=>[x,x]),['__custom','Skriv ett eget GT / sök i registret']]){const option=document.createElement('option');option.value=value;option.textContent=label;$('presetGT').append(option);}}catch(e){$('linkState').textContent=token?e.message:'Du behöver en personlig uppladdningslänk från SWNWORKS. Kontakta info@swnworks.se.';$('uploadForm').hidden=true;}}
$('presetGT').onchange=()=>{$('gt').value=$('presetGT').value==='__custom'?'':$('presetGT').value;if($('presetGT').value==='__custom')$('gt').focus();};
$('gt').oninput=()=>{clearTimeout(timer);const query=$('gt').value.trim(),sequence=++searchSequence;if(query.length<2)return;timer=setTimeout(async()=>{try{const result=await api('search',{query});if(sequence!==searchSequence)return;$('playerGTs').replaceChildren();for(const player of result.players){const option=document.createElement('option');option.value=player.display_gamertag;$('playerGTs').append(option);}}catch{}},300);};
$('file').onchange=()=>{if(previewUrl)URL.revokeObjectURL(previewUrl);const file=$('file').files[0];$('preview').hidden=true;$('uploadStatus').textContent='';if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8388608||!file.size){$('file').value='';return error(new Error('Välj JPG, PNG eller WEBP på högst 8 MB.'));}previewUrl=URL.createObjectURL(file);$('preview').src=previewUrl;$('preview').hidden=false;};
$('uploadForm').onsubmit=async event=>{event.preventDefault();if(!$('consent').checked||!info)return;$('send').disabled=true;$('uploadStatus').textContent='Laddar upp bilden…';try{const form=new FormData();form.set('gt',$('gt').value.trim());form.set('file',$('file').files[0]);form.set('consent','yes');form.set('consentVersion',info.consentVersion);const saved=await api('upload',form);$('uploadForm').hidden=true;$('success').hidden=false;$('uploadStatus').textContent='';try{info=await api('info');$('linkState').textContent=info.remaining+' uppladdningar återstår.';$('another').hidden=info.remaining<1;}catch{$('another').hidden=saved.remaining<1;}}catch(e){error(e);}finally{$('send').disabled=false;}};
$('another').onclick=()=>{$('uploadForm').reset();$('preview').hidden=true;$('success').hidden=true;$('uploadForm').hidden=false;};init();})();
