(()=>{'use strict';
const $=id=>document.getElementById(id),cfg=window.EHOCKEY_CONFIG,endpoint=cfg.supabaseUrl+'/functions/v1/swn-image-upload',token=location.hash.slice(1);
let info,previewUrl,timer,searchSequence=0;
async function api(action,data={}){const multipart=data instanceof FormData;if(multipart){data.set('action',action);data.set('token',token);}const response=await fetch(endpoint,{method:'POST',headers:multipart?{apikey:cfg.supabasePublishableKey}:{apikey:cfg.supabasePublishableKey,'Content-Type':'application/json'},body:multipart?data:JSON.stringify({action,token,...data})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to submit. Please try again.');return result;}
function error(e){$('uploadStatus').textContent=e.message;}
function suggestions(registered=[]){const query=$('gt').value.trim().toLowerCase(),names=[...new Set([...(info?.presets||[]),...registered.map(p=>p.display_gamertag)])].filter(name=>name.toLowerCase().includes(query));$('playerGTs').replaceChildren();for(const name of names){const option=document.createElement('option');option.value=name;$('playerGTs').append(option);}}
const remainingText=n=>n+' upload'+(n===1?'':'s')+' remaining on this link.';
async function init(){try{info=await api('info');$('linkName').textContent=info.name;$('linkState').textContent=remainingText(info.remaining);$('consentText').textContent=info.consentText;$('uploadForm').hidden=info.remaining<1;if(info.remaining<1)$('linkState').textContent='This link has reached its upload limit. Contact SWNWORKS if you need to send more photos.';suggestions();}catch(e){$('linkState').textContent=token?e.message:'You need a personal upload link from SWNWORKS. Contact info@swnworks.se.';$('uploadForm').hidden=true;}}
$('gt').oninput=()=>{clearTimeout(timer);suggestions();const query=$('gt').value.trim(),sequence=++searchSequence;if(query.length<2)return;timer=setTimeout(async()=>{try{const result=await api('search',{query});if(sequence===searchSequence)suggestions(result.players);}catch{}},300);};
$('file').onchange=()=>{if(previewUrl)URL.revokeObjectURL(previewUrl);const file=$('file').files[0];$('preview').hidden=true;$('uploadStatus').textContent='';if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8388608||!file.size){$('file').value='';return error(new Error('Choose a JPG, PNG or WEBP image up to 8 MB.'));}previewUrl=URL.createObjectURL(file);$('preview').src=previewUrl;$('preview').hidden=false;};
$('uploadForm').onsubmit=async event=>{event.preventDefault();if(!$('consent').checked||!info)return;$('send').disabled=true;$('uploadStatus').textContent='Uploading your photo...';try{const form=new FormData();form.set('gt',$('gt').value.trim());form.set('file',$('file').files[0]);form.set('consent','yes');form.set('consentVersion',info.consentVersion);const saved=await api('upload',form);$('uploadForm').hidden=true;$('success').hidden=false;$('uploadStatus').textContent='';try{info=await api('info');$('linkState').textContent=remainingText(info.remaining);$('another').hidden=info.remaining<1;}catch{$('another').hidden=saved.remaining<1;}}catch(e){error(e);}finally{$('send').disabled=false;}};
$('another').onclick=()=>{$('uploadForm').reset();suggestions();$('preview').hidden=true;$('success').hidden=true;$('uploadForm').hidden=false;};init();})();
