(()=>{'use strict';const $=id=>document.getElementById(id),cfg=window.EHOCKEY_CONFIG,endpoint=cfg.supabaseUrl+'/functions/v1/swn-image-upload',esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));let state={links:[],submissions:[],counts:[]},players=[];
const status=text=>$('adminStatus').textContent=text;
async function api(action,data={}){const session=await window.SWNStudioAccess.session(),multipart=data instanceof FormData;if(multipart)data.set('action',action);const response=await fetch(endpoint,{method:'POST',headers:multipart?{apikey:cfg.supabasePublishableKey,Authorization:'Bearer '+session.access_token}:{apikey:cfg.supabasePublishableKey,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:multipart?data:JSON.stringify({action,...data})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Åtgärden misslyckades.');return result;}
async function run(button,task){button.disabled=true;try{await task();}catch(e){status(e.message);}finally{button.disabled=false;}}
const stamp=value=>new Date(value).toLocaleString('sv-SE',{timeZone:'Europe/Stockholm'});
const linkUrl=link=>'https://swnworks.se/image-upload/#'+link.token;
async function refresh(){state=await api('admin-list');render();status('Bilder och länkar uppdaterade.');}
function render(){
 const filter=$('linkFilter').value;$('linkFilter').innerHTML='<option value="">Alla länkar</option>'+state.links.map(link=>'<option value="'+esc(link.id)+'">'+esc(link.name)+'</option>').join('');$('linkFilter').value=filter;
 $('links').innerHTML=state.links.length?state.links.map(link=>{const used=state.counts.find(x=>x.link_id===link.id)?.used||0;return '<article class="link-card" data-link="'+esc(link.id)+'"><h3>'+esc(link.name)+'</h3><p class="muted">'+used+' / '+link.upload_limit+' uppladdningar · '+(link.active?'Öppen':'Stängd')+' · '+stamp(link.created_at)+'</p><a class="link-url" href="'+esc(linkUrl(link))+'" target="_blank" rel="noopener noreferrer">'+esc(linkUrl(link))+'</a><div class="row"><button data-copy class="secondary">Kopiera länk</button><label>Gräns <input data-limit type="number" min="1" max="500" value="'+link.upload_limit+'"></label><button data-save>Spara gräns</button><button data-toggle class="secondary">'+(link.active?'Stäng länk':'Öppna länk')+'</button></div></article>';}).join(''):'<p class="muted">Inga länkar ännu. Skapa din första till vänster.</p>';
 for(const card of $('links').querySelectorAll('[data-link]')){const link=state.links.find(x=>x.id===card.dataset.link);card.querySelector('[data-copy]').onclick=()=>run(card.querySelector('[data-copy]'),async()=>{await navigator.clipboard.writeText(linkUrl(link));status('Länken är kopierad.');});card.querySelector('[data-save]').onclick=()=>run(card.querySelector('[data-save]'),async()=>{await api('admin-link-update',{id:link.id,limit:Number(card.querySelector('[data-limit]').value),active:link.active});await refresh();});card.querySelector('[data-toggle]').onclick=()=>run(card.querySelector('[data-toggle]'),async()=>{await api('admin-link-update',{id:link.id,limit:link.upload_limit,active:!link.active});await refresh();});}
 renderSubmissions();
}
function renderSubmissions(){
 const filter=$('linkFilter').value,rows=state.submissions.filter(row=>!filter||row.link_id===filter);
 $('submissions').innerHTML=rows.length?rows.map(row=>{const link=state.links.find(x=>x.id===row.link_id),done=['published','rejected'].includes(row.status);return '<article class="submission" data-id="'+esc(row.id)+'"><h3>'+esc(row.submitted_gt)+'</h3><p class="muted">Länk: '+esc(link?.name||row.link_id)+' · '+stamp(row.uploaded_at||row.created_at)+' · '+esc({pending:'Väntar på granskning',editing:'Redigeras',published:'Publicerad',rejected:'Avslagen'}[row.status]||row.status)+'</p><button data-original class="secondary">Visa original / hämta bild</button><div data-preview></div><details><summary>Godkännande</summary><div class="submitted-consent">'+esc(row.consent_text)+'<br><b>'+stamp(row.consent_at)+'</b> · '+esc(row.consent_version)+'</div></details>'+(done?(row.published_url?'<a href="'+esc(row.published_url)+'" target="_blank" rel="noopener">Visa publicerad bild</a>':''):'<label>Sök rätt spelare i registret<input data-query value="'+esc(row.submitted_gt)+'" maxlength="80"></label><button data-search class="secondary">Sök spelare</button><label>Bekräfta rätt registrerad spelare<select data-player><option value="">Sök och välj en spelare</option></select></label><label class="file-label">Färdigredigerad bild<input data-file type="file" accept="image/png,image/jpeg,image/webp"></label><div class="row"><button data-publish>Publicera till vald spelare</button><button data-reject class="danger">Avslå bild</button></div>')+'<p data-status class="status" role="status"></p></article>';}).join(''):'<p class="muted">Inga inskickade bilder för den här länken.</p>';
 for(const card of $('submissions').querySelectorAll('[data-id]')){
 const row=rows.find(x=>x.id===card.dataset.id),cardStatus=text=>card.querySelector('[data-status]').textContent=text;
 card.querySelector('[data-original]').onclick=()=>run(card.querySelector('[data-original]'),async()=>{const result=await api('admin-original',{id:row.id});card.querySelector('[data-preview]').innerHTML='<img src="'+esc(result.url)+'" alt="Originalbild för '+esc(row.submitted_gt)+'"><a href="'+esc(result.url)+'" target="_blank" rel="noopener noreferrer">Öppna original i ny flik · länken gäller i 10 minuter</a>';});
 if(!card.querySelector('[data-search]'))continue;
 card.querySelector('[data-search]').onclick=()=>run(card.querySelector('[data-search]'),async()=>{const result=await api('admin-search',{query:card.querySelector('[data-query]').value});card.querySelector('[data-player]').innerHTML='<option value="">Välj rätt spelare</option>'+result.players.map(player=>'<option value="'+esc(player.player_key)+'">'+esc(player.display_gamertag)+' · '+esc(player.player_key)+'</option>').join('');cardStatus(result.players.length?'Välj rätt spelare före publicering.':'GT hittades inte. Sök ett annat GT eller registrera spelaren först.');});
 card.querySelector('[data-publish]').onclick=()=>run(card.querySelector('[data-publish]'),async()=>{const key=card.querySelector('[data-player]').value,file=card.querySelector('[data-file]').files[0];if(!key||!file)throw new Error('Välj registrerad spelare och en redigerad bild.');if(!confirm('Publicera den redigerade bilden för '+card.querySelector('[data-player]').selectedOptions[0].textContent+'?'))return;const data=new FormData();data.set('id',row.id);data.set('playerKey',key);data.set('file',file);cardStatus('Publicerar…');await api('admin-publish',data);await refresh();status('Bilden är publicerad till spelarprofilen. Studiorna hämtar den vid nästa datauppdatering.');});
 card.querySelector('[data-reject]').onclick=()=>run(card.querySelector('[data-reject]'),async()=>{await api('admin-reject',{id:row.id});await refresh();});
 }
}
$('createLink').onsubmit=event=>{event.preventDefault();run($('createButton'),async()=>{await api('admin-create',{name:$('linkName').value.trim(),limit:Number($('linkLimit').value),presets:$('presetGTs').value});await refresh();status('Den unika länken är skapad. Kopiera den och dela med spelarna.');});};$('refresh').onclick=()=>run($('refresh'),refresh);$('linkFilter').onchange=renderSubmissions;
async function loadTeams(){players=[];for(let offset=0;;offset+=1000){const params=new URLSearchParams({select:'sports_gamer_player_id,sports_gamer_team_id,sports_gamer_league_id,team_name_in_league,display_gamertag',order:'sports_gamer_league_id,sports_gamer_team_id,sports_gamer_player_id',limit:'1000',offset:String(offset)});const response=await fetch(cfg.supabaseUrl+'/rest/v1/v_broadcast_players_public?'+params,{headers:{apikey:cfg.supabasePublishableKey}});if(!response.ok)return;const page=await response.json();players.push(...page);if(page.length<1000)break;}const teams=new Map();for(const p of players){const key=p.sports_gamer_league_id+':'+p.sports_gamer_team_id;if(p.team_name_in_league&&!teams.has(key))teams.set(key,p);}for(const [key,p]of [...teams].sort((a,b)=>a[1].team_name_in_league.localeCompare(b[1].team_name_in_league,'sv'))){const option=document.createElement('option');option.value=key;option.textContent=p.team_name_in_league+' � liga '+p.sports_gamer_league_id;$('presetTeam').append(option);}}
$('presetTeam').onchange=()=>{const key=$('presetTeam').value;const gts=[...new Set(players.filter(p=>p.sports_gamer_league_id+':'+p.sports_gamer_team_id===key).map(p=>p.display_gamertag))].sort();$('presetGTs').value=gts.join('\n');if(gts.length)$('linkLimit').value=gts.length;};refresh().catch(e=>status(e.message));loadTeams().catch(()=>{});
})();
